### ISSUE TITLE
Modify the importaddress function to accept a starting height for rescan

### ISSUE THREAD

**Issue by AegeusCoin** [AegeusCoin/aegeus#20]
The current method for key discovery in the sharing prototype scans as far back as genesis for a registration transaction for the address being imported.  As the prototype was not around going back that far in history - it would make more sense to include the option to specify a starting height for this address.  Addresses will have only been 'registered' for sharing purposes starting at the height near the height on or after the release of the prototype.

**Comment by AegeusCoin** [comment]
Addressed/completed here: https://github.com/AegeusCoin/aegeus/pull/21

**Comment by tdiesler** [comment]
Here some ideas and concerns about this ...

* How will the wallet behave when an user imports a privkey that has utxo from before the given height?

* AEG is now at blockheight 400.000 i.e. 278 days. How will the wallet behave in one year from now?

Generally, I believe that there cannot be a compromise between utxo integrity and performance of an the import operation. Instead, a full scan of the available blocks must always happen. To address the performance issue, the import could perhaps be done asynchronously. This would then be similar to wallet behavior on startup - most functionality is available while the wallet updates the blockchain in the background.

Moreover, in a year from now and even longer term it may be unrealistic to require users to run full nodes because of initial download time and disk space restrictions. For example, the Bitcoin Testnet currently contains 6 years of data with a total of 23GB of data. Few people would use a Bitcoin app that requires a download of so much data, that is likely also irrelevant to the app.

Bitcoin has a [prune](https://bitcoin.org/en/developer-reference#pruneblockchain) option, which addresses this scenario. Similarly, the AEG blockchain could also support pruning, which may make the need for async import obsolete - because there arn't that many blocks to scan.

**Comment by AegeusCoin** [comment]
Coded and merged: https://github.com/AegeusCoin/aegeus/pull/21
